name: Run ESLint to /src
on:
  pull_request:
    branches: 
      - [dev]
jobs:
  eslint:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.0
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: install dependencies
        run: npm install
      
      - name: Run linter
        run: npm run lint